-- CREATE operation with inline syntax of constraints
--CREATE TABLE EMPLOYEE(
--	EMPLOYEE_ID 	INT 	PRIMARY KEY,
--	EMPLOYEE_NAME 	VARCHAR(20) NOT NULL,
--    EMPLOYEE_SALARY INT 	DEFAULT 1000 
--								CHECK ----(EMPLOYEE_SALARY<=150000)
--);

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID 	INT,
	EMPLOYEE_NAME 	VARCHAR(20),
	EMPLOYEE_SALARY INT
);

-- outline syntax :: Primary Key
ALTER TABLE EMPLOYEE
ADD CONSTRAINT NN_EMPLOYEE_NAME
CHECK (EMPLOYEE_NAME IS NOT NULL);

ALTER TABLE EMPLOYEE
DROP CONSTRAINT NN_EMPLOYEE_NAME;

-- tightly coupling NULL and then adding Primary Key
ALTER TABLE EMPLOYEE
ALTER COLUMN EMPLOYEE_ID INT NOT NULL;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_EMPLOYEE_ID
PRIMARY KEY (EMPLOYEE_ID);

-- dropping primary key and then dropping tightly coupled NULL
ALTER TABLE EMPLOYEE
DROP CONSTRAINT PK_EMPLOYEE_ID;

ALTER TABLE EMPLOYEE
ALTER COLUMN EMPLOYEE_ID INT NULL;

-- outline syntax
ALTER TABLE EMPLOYEE
ADD CONSTRAINT CK_EMPLOYEE_SALARY
CHECK(EMPLOYEE_SALARY<=15000);

ALTER TABLE EMPLOYEE
DROP CONSTRAINT CK_EMPLOYEE_SALARY;

-- outline syntax of default constraint
ALTER TABLE EMPLOYEE
ADD CONSTRAINT DF_EMPLOYEE_SALARY
DEFAULT 2000 FOR EMPLOYEE_SALARY;

ALTER TABLE EMPLOYEE
DROP CONSTRAINT DF_EMPLOYEE_SALARY;
-- DROP CONSTRAINT DF__EMPLOYEE__EMPLOY__5165187F;

-------------------------------------------------------
-------------------------------------------------------
-- LINKING TO a different table DEPARTMENT
CREATE TABLE DEPARTMENT(
	DEPARTMENT_ID NUMERIC(2),
	DEPARTMENT_NAME VARCHAR(56)
);


-- adding constraints
ALTER TABLE DEPARTMENT
ALTER COLUMN DEPARTMENT_ID NUMERIC(2) NOT NULL;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT PK_DEPARTMENT_ID
PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT NN_DEPARTMENT_NAME
CHECK (DEPARTMENT_NAME IS NOT NULL);

-- adding the department ID column and declaring it as a foreign key
ALTER TABLE EMPLOYEE
ADD DEPARTMENT_ID NUMERIC(2) FOREIGN KEY
REFERENCES DEPARTMENT(DEPARTMENT_ID);

-- outline syntax of adding foreign key
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_DEPARTMENT_ID
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENT(DEPARTMENT_ID);

-- DROP CONSTRAINT CK__EMPLOYEE__EMPLOY__4CA06362;



-- DELETE operation
DROP TABLE EMPLOYEE;